version: '3.1'

services:
    owt-immersive-4k:
        image: xeon-centos76-service-owt-immersive
        command: >
            sh -c "/home/init.sh
            && /home/start.sh
            && /home/restApi.sh -s 4k
            && /home/restart.sh
            && /home/restApi.sh -c /home/Sample-Videos/test1_h265_3840x2048_30fps_30M_200frames.mp4
            && /home/sleep.sh"
        network_mode: host
        volumes:
            - ../../../Sample-Videos:/home/Sample-Videos

    owt-immersive-8k:
        image: xeon-centos76-service-owt-immersive
        command: >
            sh -c "/home/init.sh
            && /home/start.sh
            && /home/restApi.sh -s 8k
            && /home/restart.sh
            && /home/restApi.sh -c /home/Sample-Videos/test1_h265_8k_30fps_60M_100frames.mp4
            && /home/sleep.sh"
        network_mode: host
        volumes:
            - ../../../Sample-Videos:/home/Sample-Videos
