apiVersion: v1
kind: Service
metadata:
  name: immersive-service
  labels:
    app: immersive-server
spec:
  type: NodePort
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
    nodePort: 5000
    name: https
  - port: 8080
    targetPort: 8080
    nodePort: 5001
    name: http
  externalIPs:
    - 10.67.119.226
  selector:
    app: immersive-server
